In [5]:
import torch 
import torch.nn as nn
input = torch.randn(3, 10)
input2 = torch.randn(5, 3, 10)
rnn_origin = nn.RNN(10, 20, 2, batch_first=True)
output, hn = rnn_origin(input)

print(output.size()) # [batch_size, seq_length, h_out]
print(hn.size())   # [num_layers, batch_size, h_out]


rnn_origin = nn.RNN(10, 20, 2)
output, hn = rnn_origin(input2)
# rnn_origin = nn.RNN(20, 20, 1, batch_first=True)
# output, hn = rnn_origin(output)
print(output.size()) # [batch_size, seq_length, h_out]
print(hn.size())   # [num_layers, batch_size, h_out]



torch.Size([3, 20])
torch.Size([2, 20])
torch.Size([5, 3, 20])
torch.Size([2, 3, 20])


In [12]:
x = torch.arange(2, 3, 0.1)
x = x.view(-1, 2)
print(x.size())
print(x)

for idx in range(x.size(0)):
    print(x[idx, :])

torch.Size([5, 2])
tensor([[2.0000, 2.1000],
        [2.2000, 2.3000],
        [2.4000, 2.5000],
        [2.6000, 2.7000],
        [2.8000, 2.9000]])
tensor([2.0000, 2.1000])
tensor([2.2000, 2.3000])
tensor([2.4000, 2.5000])
tensor([2.6000, 2.7000])
tensor([2.8000, 2.9000])


In [3]:
from nlp.models.rnn import RNN

input = torch.randn(5, 3, 10)

rnn_custom = RNN(input_size=10, hidden_size=20, num_layers=1)
rnn_custom(input)


NameError: name 'RNN' is not defined

__main__.RNN2